### ISSUE TITLE
Creating Duplicate record in v 17.0

### ISSUE THREAD

**Issue by mosilix** [Yenthe666/mail#3]
I have tested this with CRM lead in v17 and it is creating duplicate record is created after fetching a new email, 
After debugging I realized that the create method is called double times, once from message_new and the other one from _mail_parser_custom.  Looks like there is a problem with _mail_parser_custom.

**Comment by flotho** [comment]
Hi @mosilix , same thing here in v16.
did you pointed the code part responsible on this ?
Regards

**Comment by flotho** [comment]
Hum @mosilix did you have the issue with only this module installed or do you have other modules installed changibg mail behaviour ?
Regards

**Comment by flotho** [comment]
Hi @mosilix , could you have a look to https://github.com/Yenthe666/mail/pull/4 ?
Regards
